// Built-in demo catalog. Garment art lives in /public/garments/*.svg so the app
// works fully offline. Real photo garments come in via the scraper adapter
// (import from a retailer URL) or a future per-retailer API adapter.
export const CATALOG = [
  {
    id: 'mock:sh-tee-white',
    source: 'mock',
    retailer: 'StyleHub',
    title: 'Essential Cotton Tee',
    brand: 'StyleHub Basics',
    price: 24.0,
    currency: 'USD',
    category: 'tops',
    thumbnail: '/garments/tee-white.svg',
    garmentImage: '/garments/tee-white.svg',
    productUrl: 'https://example.com/stylehub/essential-tee',
  },
  {
    id: 'mock:sh-hoodie-slate',
    source: 'mock',
    retailer: 'StyleHub',
    title: 'Heavyweight Hoodie',
    brand: 'StyleHub Basics',
    price: 58.0,
    currency: 'USD',
    category: 'tops',
    thumbnail: '/garments/hoodie-slate.svg',
    garmentImage: '/garments/hoodie-slate.svg',
    productUrl: 'https://example.com/stylehub/heavyweight-hoodie',
  },
  {
    id: 'mock:sh-dress-rose',
    source: 'mock',
    retailer: 'StyleHub',
    title: 'Summer Slip Dress',
    brand: 'StyleHub',
    price: 72.0,
    currency: 'USD',
    category: 'dresses',
    thumbnail: '/garments/dress-rose.svg',
    garmentImage: '/garments/dress-rose.svg',
    productUrl: 'https://example.com/stylehub/summer-slip-dress',
  },
  {
    id: 'mock:sh-shirt-blue',
    source: 'mock',
    retailer: 'StyleHub',
    title: 'Oxford Button-Down',
    brand: 'StyleHub',
    price: 49.0,
    currency: 'USD',
    category: 'tops',
    thumbnail: '/garments/shirt-blue.svg',
    garmentImage: '/garments/shirt-blue.svg',
    productUrl: 'https://example.com/stylehub/oxford-shirt',
  },
  {
    id: 'mock:ut-jacket-olive',
    source: 'mock',
    retailer: 'Urban Threads',
    title: 'Utility Field Jacket',
    brand: 'Urban Threads',
    price: 128.0,
    currency: 'USD',
    category: 'outerwear',
    thumbnail: '/garments/jacket-olive.svg',
    garmentImage: '/garments/jacket-olive.svg',
    productUrl: 'https://example.com/urban-threads/field-jacket',
  },
  {
    id: 'mock:ut-tee-black',
    source: 'mock',
    retailer: 'Urban Threads',
    title: 'Boxy Graphic Tee',
    brand: 'Urban Threads',
    price: 32.0,
    currency: 'USD',
    category: 'tops',
    thumbnail: '/garments/tee-black.svg',
    garmentImage: '/garments/tee-black.svg',
    productUrl: 'https://example.com/urban-threads/boxy-tee',
  },
  {
    id: 'mock:ut-dress-navy',
    source: 'mock',
    retailer: 'Urban Threads',
    title: 'Knit Midi Dress',
    brand: 'Urban Threads',
    price: 89.0,
    currency: 'USD',
    category: 'dresses',
    thumbnail: '/garments/dress-navy.svg',
    garmentImage: '/garments/dress-navy.svg',
    productUrl: 'https://example.com/urban-threads/knit-midi',
  },
  {
    id: 'mock:ut-hoodie-cream',
    source: 'mock',
    retailer: 'Urban Threads',
    title: 'Zip-Up Fleece',
    brand: 'Urban Threads',
    price: 64.0,
    currency: 'USD',
    category: 'outerwear',
    thumbnail: '/garments/hoodie-cream.svg',
    garmentImage: '/garments/hoodie-cream.svg',
    productUrl: 'https://example.com/urban-threads/zip-fleece',
  },
]
