import { useEffect, useState } from 'react'
import { compositeOverlay } from '../lib/image.js'

export default function TryOnResult({ result, product, person, onBack, onHome }) {
  const [image, setImage] = useState(null)
  const [building, setBuilding] = useState(true)
  const [note, setNote] = useState(result?.note || null)

  useEffect(() => {
    let cancelled = false
    async function build() {
      setBuilding(true)
      if (result.mode === 'overlay') {
        // Mock engine: composite garment over the photo on-device.
        const src = await compositeOverlay(result.image || person, result.overlay || product.garmentImage)
        if (!cancelled) setImage(src)
      } else {
        if (!cancelled) setImage(result.image)
      }
      if (!cancelled) setBuilding(false)
    }
    build().catch(() => { if (!cancelled) { setImage(result.image || person); setBuilding(false) } })
    return () => { cancelled = true }
  }, [result, person, product])

  const download = () => {
    const a = document.createElement('a')
    a.href = image
    a.download = `tryon-${product.id.replace(/[^a-z0-9]+/gi, '-')}.png`
    a.click()
  }

  const share = async () => {
    try {
      const blob = await (await fetch(image)).blob()
      const file = new File([blob], 'tryon.png', { type: blob.type })
      if (navigator.canShare?.({ files: [file] })) {
        await navigator.share({ files: [file], title: product.title, text: `Trying on ${product.title}` })
      } else {
        download()
      }
    } catch { /* user cancelled share */ }
  }

  return (
    <div className="result">
      <button className="back" onClick={onBack}>← Back</button>
      <h1 className="detail-title">{product.title}</h1>

      <div className="result-stage">
        {building ? (
          <div className="result-loading">
            <div className="spinner" />
            <p>Generating your look…</p>
          </div>
        ) : (
          <img className="result-img" src={image} alt="Try-on result" />
        )}
      </div>

      {note && <p className="muted small note">{note}</p>}
      {result.engine && result.mode !== 'overlay' && (
        <p className="muted small">Generated by {result.engine} in {(result.ms / 1000).toFixed(1)}s</p>
      )}

      <div className="result-actions">
        <button className="btn primary" disabled={building} onClick={share}>Share</button>
        <button className="btn" disabled={building} onClick={download}>Save</button>
        <button className="btn ghost" onClick={onHome}>Try another</button>
      </div>
    </div>
  )
}
